### ISSUE TITLE
Always fails when reading as compiled score

### ISSUE THREAD

**Issue by blueapple25130** [hozuki/MilliSim#2]
https://github.com/hozuki/MilliSim/blob/e94b0e9bd34fe2c21a62c89adf4a0a2e4e175726/OpenMLTD.MilliSim.Theater/Elements/Logical/ScoreLoader.cs#L86-L97

Maybe, missing code `successful = true;` under the line 89.

**Comment by hozuki** [comment]
Thanks. I haven't tested this branch. 😛
